package vista;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.


/**
 *
 * @author Sala319
 */
public class FrmOficinas extends javax.swing.JFrame {
    DefaultTableModel Modelo_Oficina;
  //  String data[][]={};
  // String ofic[]={"codi_ofic","Codi_Tipo","Email","Telefono"};
    
    
    

    public FrmOficinas() {
        initComponents();
        setSize(700, 400);
       //Modelo_Oficina=new DefaultTableModel(data, ofic);
        
       // Modelo_Oficina.addColumn("Codi_Ofic");
      //  Modelo_Oficina.addColumn("Nomb_Ofic");
       //  Modelo_Oficina.addColumn("Telefono");
     //   Modelo_Oficina.addColumn("Email");
       // this.Tabla.setModel(Modelo_Oficina);
    }
    
    public boolean isEmail(String correo) {
        Pattern pat = null;
        Matcher mat = null;        
        pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z]"
                + "[-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        mat = pat.matcher(correo);
        if (mat.find()) {
            //System.out.println("[" + mat.group() + "]");
            return true;
        }else{
            return false;
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codi_ofic = new javax.swing.JTextField();
        codigo = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        nombreoficina = new javax.swing.JLabel();
        adicionar = new javax.swing.JButton();
        jtexoficina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD Oficinas");
        setResizable(false);
        getContentPane().setLayout(null);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 200, 432, 120);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(294, 33, 0, 0);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(294, 33, 0, 0);

        codi_ofic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codi_oficActionPerformed(evt);
            }
        });
        codi_ofic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codi_oficKeyTyped(evt);
            }
        });
        getContentPane().add(codi_ofic);
        codi_ofic.setBounds(110, 10, 120, 30);

        codigo.setText("Código de Oficina:");
        getContentPane().add(codigo);
        codigo.setBounds(10, 10, 90, 30);

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(Telefono);
        Telefono.setBounds(110, 50, 120, 30);

        telefono.setText("Teléfono:");
        getContentPane().add(telefono);
        telefono.setBounds(30, 50, 60, 30);

        email.setText("Email:");
        getContentPane().add(email);
        email.setBounds(410, 50, 40, 30);

        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });
        getContentPane().add(Email);
        Email.setBounds(500, 50, 150, 30);

        nombreoficina.setText("Nombre de la Oficina:");
        getContentPane().add(nombreoficina);
        nombreoficina.setBounds(390, 10, 110, 30);

        adicionar.setText("Agregar Oficina");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });
        getContentPane().add(adicionar);
        adicionar.setBounds(270, 160, 110, 23);

        jtexoficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtexoficinaActionPerformed(evt);
            }
        });
        getContentPane().add(jtexoficina);
        jtexoficina.setBounds(500, 10, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codi_oficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codi_oficActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_codi_oficActionPerformed

    private void codi_oficKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codi_oficKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9')evt.consume();
        
        String cadena = codi_ofic.getText();
        if(cadena.length() >=3)evt.consume();
    }//GEN-LAST:event_codi_oficKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9')evt.consume();
        
        String cadena = Telefono.getText();
        if(cadena.length() >=7)evt.consume();
    }//GEN-LAST:event_TelefonoKeyTyped

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
        // TODO add your handling code here:
           if(!isEmail(Email.getText())){
            JOptionPane.showMessageDialog(rootPane, "No es un correo válido");
            Email.requestFocus();   
            Email.selectAll();
        }
    }//GEN-LAST:event_EmailFocusLost

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped
        // TODO add your handling code here:
          String Cadena = Email.getText();
        if (Cadena.length() >= 60)evt.consume();
    }//GEN-LAST:event_EmailKeyTyped

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarActionPerformed

    private void jtexoficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtexoficinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtexoficinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOficinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmOficinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Email;
    public javax.swing.JTable Tabla;
    public javax.swing.JTextField Telefono;
    public javax.swing.JButton adicionar;
    public javax.swing.JTextField codi_ofic;
    public javax.swing.JLabel codigo;
    public javax.swing.JLabel email;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jtexoficina;
    public javax.swing.JLabel nombreoficina;
    public javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables
}
